<a href="https://colab.research.google.com/github/neilrosario27/PowerPlantOutput_ANN/blob/main/ANN_Power_Plant_Output.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DATA PREPROCESSING

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [3]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')

In [4]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [6]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

ANN

In [8]:
ann = tf.keras.models.Sequential()

In [11]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [12]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [16]:
ann.add(tf.keras.layers.Dense(units = 1))

In [17]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

ANN TRAINING

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 4s 2ms/step - loss: 128055.9375
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 399.9769
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 336.8182
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 329.4165
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 321.0477
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 310.5015
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 299.0833
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 286.9475
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 272.9201
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 258.9946
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 244.1297
Epoch 12/100
240/240 [==============================] - 0s 2ms/step - l

In [19]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 1ms/step
[[452.63 458.96]
 [461.61 463.29]
 [436.99 435.27]
 ...
 [476.52 476.22]
 [422.82 440.29]
 [463.91 467.92]]
